### ISSUE TITLE
Permission 'http://*/*' is unknown or URL pattern is malformed.

### ISSUE THREAD

**Issue by KendallDoesCoding** [aliraza944/Log-View-Extension#1]
Getting this error when loading extension into chrome, idk if the extension works or no though, still haven't tested it.

![image](https://user-images.githubusercontent.com/84712013/151656412-7f7f1159-18a2-46df-83b3-0e448914e94d.png)

**Comment by aliraza944** [comment]
@KendallDoesCoding  The extension is working fine on my side. I'll take a look at it.

**Comment by KendallDoesCoding** [comment]
Yup, this is fixed. Not getting any more chrome issues. Thanks!
